### ISSUE TITLE
2 copyrights in the login/signup page

### ISSUE THREAD

**Issue by MrDBC** [Dhruvermafz/social-app#3]
>1 **There are 2 copyrights in the signup page**

![Screenshot 2023-10-15 093535](https://github.com/Dhruvermafz/social-app/assets/69349350/4f93f058-c1da-4581-a8ed-7bbc4946c227)

>2 **Also if i remove one of them, its not placed at the perfect place**

![Screenshot 2023-10-15 095048](https://github.com/Dhruvermafz/social-app/assets/69349350/7a365468-a633-4e80-9d9b-67a06056ca01)

**Comment by MrDBC** [comment]
@Dhruvermafz 
can you assign this to me?
and give the hacktoberfest tags as well

**Comment by Dhruvermafz** [comment]
do it dude but im on updating the stuff

**Comment by MrDBC** [comment]
@Dhruvermafz 
you can raise an issue , what changes you need
Im willing to work on it

**Comment by Dhruvermafz** [comment]
Dude that's really noice and can you help me build this web

**Comment by MrDBC** [comment]
@Dhruvermafz 
yes why not
but the problem is I have just joined an organization 2 weeks back
so i cant invest more than 1-2 hrs on weekdays
i can invest more hours on the weekends for sure

I wanted to give my context, 
and yes lets do it

what features/bug you want to add/solve?
