### ISSUE TITLE
[Improvement] improve the user interface

### ISSUE THREAD

**Issue by ChiragAgg5k** [Dhruvermafz/social-app#7]
As apparent from the screenshot, the user interface is very mis-aligned. I can work on this under the hacktoberfest label

<img width="1392" alt="Screenshot 2023-10-16 at 9 14 02 AM" src="https://github.com/Dhruvermafz/social-app/assets/110609663/360715a0-3c38-4f83-9027-5c8084080cf0">

**Comment by Dhruvermafz** [comment]
sir im working for the improvements currently thanks for your offer for help
